dist: trusty
sudo: required
language: python
matrix:
    include:
        - python: 2.7
          env: LATEST="false" NUMPY_VERSION="1.11" SCIPY_VERSION="0.18" SKLEARN_VERSION="0.18" MATPLOTLIB_VERSION="2.0" PANDAS_VERSION="0.19" NLTK_VERSION="3.2" TENSORFLOW_VERSION="1.3"
        - python: 3.5
          env: LATEST="false" NUMPY_VERSION="1.11" SCIPY_VERSION="0.18" SKLEARN_VERSION="0.18" MATPLOTLIB_VERSION="2.0" PANDAS_VERSION="0.19" NLTK_VERSION="3.2" TENSORFLOW_VERSION="1.3"
        - python: 3.6
          env: LATEST="false" NUMPY_VERSION="1.11" SCIPY_VERSION="0.18" SKLEARN_VERSION="0.18" MATPLOTLIB_VERSION="2.0" PANDAS_VERSION="0.19" NLTK_VERSION="3.2" TENSORFLOW_VERSION="1.3"
        - python: 3.6
          env: LATEST="false" NUMPY_VERSION="1.13" SCIPY_VERSION="0.19" SKLEARN_VERSION="0.19" MATPLOTLIB_VERSION="2.0" PANDAS_VERSION="0.20" NLTK_VERSION="3.2" TENSORFLOW_VERSION="1.3"
        - python: 3.6
          env: LATEST="true"

addons:
  apt:
    packages:
      - graphviz

install:
    - sudo apt-get update
    - source .travis/install_travis_env.sh

before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
    - bash .travis/run_travis_tests.sh
#after_success:
#    - if [[ "${COVERAGE}" == "true" ]]; then coveralls; codecov; else echo "failed"; fi

notifications:
    email:
        recipients:
            - mail@sebastianraschka.com
    on_success: always
    on_failure: always
